### PR TITLE
store scope references on nodes being visited

### PR DESCRIPTION
**Pull request by magalhas**
Hi,

This is something that we need at our company, not sure if it makes sense to include this on the module, but if it fits it would avoid having to maintain a fork of escope.

Thank you :+1:

### CODE REVIEW

**Comment by magalhas** [comment]
Anyone :) ?

**Comment by magalhas** [comment]
Bump

**Comment by mysticatea** [comment]
I think escope should not rewrite AST node objects.

**Comment by Constellation** [comment]
Yes. escope should not modify the AST. If you would like to look up the scope from the node, please use the existing APIs :)

**Pull request closed without merging**
