### PR TITLE
Rewrite tests in ES2015.

### PR DESCRIPTION
**Pull request by eventualbuddha**
I used decaffeinate + esnext + a manual cleanup pass to move the tests over.

Here's the script I used:

```sh
#!/usr/bin/env bash

set -ex

DECAFFEINATE=./node_modules/.bin/decaffeinate
ESNEXT=./node_modules/.bin/esnext

coffee=$1

if [ -z "$coffee" ]; then
  echo "$(basename $0) PATH" >&2
  exit 1
fi

js="$(dirname $coffee)/$(basename $coffee .coffee).js"
$DECAFFEINATE $coffee
sed -i '' "s/return it/it/g" $js
sed -i '' "s/return describe/describe/g" $js
sed -i '' "s/return expect/expect/g" $js
sed -i '' "s/escope.analyze/analyze/g" $js
$ESNEXT $js -o $js
```

### CODE REVIEW

**Comment by michaelficarra** [comment]
Thanks. I'd love to take your word for it, but I'll run your script myself when I get home tonight to confirm. Can you also give the invocation you used?

**Comment by eventualbuddha** [comment]
Sure. To use that script it'd be something like this:

```sh
# install the converters
$ npm i decaffeinate esnext

# run the script on each test file, e.g.
$ ./convert-test.sh test/es6-class.coffee
```

**Comment by eventualbuddha** [comment]
Also, note that I did a decent number of by-hand cleanups. Most of it was re-indenting the source template strings (since escope doesn't care about the whitespace it doesn't matter if there's leading whitespace on the lines), but I also massaged the imports, changed some `for` loops to `forEach`, changed other `for` loops to unwrap the IIFE that CoffeeScript adds to collect the results when the loop is the last statement of a function, and manually converting the commented-out code to ES6.

**Comment by michaelficarra** [comment]
Wow, that was a lot to review! LGTM, thanks.

**Comment by michaelficarra** [comment]
By the way, the `sed` in your script is BSD sed. I was using GNU sed and getting errors at first.

**Comment by eventualbuddha** [comment]
Oh? What'd you change?

**Comment by michaelficarra** [comment]
I changed the script to point to a copy of BSD sed using an absolute path instead of searching for sed in my PATH.

**Pull request merged**
