### PR TITLE
Fix meta property

### PR DESCRIPTION
**Pull request by mysticatea**
From https://github.com/eslint/eslint/issues/5420

I made `escope` not creating references of `new.target`.
Before, because `MetaProperty#meta` and `MetaProperty#property` are an `Identifier`, `escope` had been creating references of them.

Further reading: https://github.com/estree/estree/blob/master/es6.md#metaproperty

### CODE REVIEW

**Comment by michaelficarra** [comment]
Thanks.

**Comment by mysticatea** [comment]
@michaelficarra Thank you! Could you make a new release?

**Comment by Constellation** [comment]
Released changes as `3.5.0`.

**Comment by mysticatea** [comment]
Thank you very much!

**Pull request merged**
