### PR TITLE
Bump deps

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by TrySound** [comment]
@michaelficarra Any chance to patch or minor release?

**Comment by michaelficarra** [comment]
@TrySound I'd prefer @Constellation made the release, but if we can't get in contact with him in the next few days, I'll do it for you. Just remind me.

**Comment by TrySound** [comment]
@michaelficarra Okay, waiting the next few days.

**Comment by Constellation** [comment]
@michaelficarra, @TrySound: Sorry. I'll check this tonight :)

**Comment by Constellation** [comment]
sorry for my delay. I've published `3.2.1` :)

**Pull request merged**
