### PR TITLE
Fixes visiting logic for ObjectPattern/ObjectExpression

### LINKED ISSUE #76: ObjectPattern/ObjectExpression incorrectly assume all children are Property
Both `ObjectPattern` and `ObjectExpression` assume that all nodes in `properties` will be of type `Property`, and that causes an error if there's ever a different node type present (such as with spread properties or rest properties).

Around here:
https://github.com/estools/escope/blob/master/src/referencer.js#L50

And here:
https://github.com/estools/escope/blob/master/src/referencer.js#L112

It should instead `visit()` each property so it can handle any node type that is present.

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #76.

### CODE REVIEW

**Comment by Constellation** [comment]
This is because `Property` type is sometimes not attached (for example, original SpiderMonkey Reflect does not attach `Property` type.)
But, now, I think we can assume `Property` is correctly attached in the all parsers. So, LGTM.

**Comment by michaelficarra** [comment]
Won't this need a major version bump?

**Comment by mysticatea** [comment]
@Constellation Thank you for the explanation. I got it.

@michaelficarra I think this needs a major version bump...

**Comment by robcolburn** [comment]
@Constellation / @michaelficarra - ping. so, version bump?

**Pull request merged**
